using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Dapper;
using Npgsql;
using NpgsqlTypes; // Needed for NpgsqlDbType

public class PostgresBulkDialect : IBulkDialect
{
    public async Task BulkMergeAsync<T>(
        IDbConnection connection,
        IDbTransaction transaction,
        List<T> entities,
        ClassMetadata metadata,
        BulkSaveOptions options) where T : class
    {
        var npgsqlConn = connection as NpgsqlConnection
            ?? throw new InvalidOperationException("Connection must be NpgsqlConnection");
        var npgsqlTrans = transaction as NpgsqlTransaction;

        // Filter props
        var savableProps = metadata.SavableProperties
            .Where(p => options.SpecificColumns == null || options.SpecificColumns.Contains(p.Property.Name))
            .ToList();

        string tempTableName = $"temp_{metadata.TableName}_{Guid.NewGuid():N}";

        try
        {
            // 1. Setup & Import
            await CreateTempTableAsync(connection, transaction, metadata, savableProps, tempTableName);
            await BinaryImportAsync(npgsqlConn, npgsqlTrans, entities, savableProps, tempTableName);

            // 2. Merge (Upsert)
            var mergeResults = await RunMergeAsync(connection, transaction, metadata, savableProps, tempTableName);

            // 3. ID Mapping
            var createdEntities = new List<T>();
            var updateIndices = new HashSet<int>();
            var autoGeneratedIds = new Queue<object>();

            foreach (var res in mergeResults)
            {
                if (res.Type == "UPDATE")
                {
                    updateIndices.Add(res.RowIndex);
                    if (res.RowIndex >= 0 && res.RowIndex < entities.Count)
                        OrmMapper.SetEntityId(entities[res.RowIndex], metadata, res.Id);
                }
                else if (res.Type == "INSERT")
                {
                    autoGeneratedIds.Enqueue(res.Id);
                }
            }

            // Map IDs to items
            for (int i = 0; i < entities.Count; i++)
            {
                if (!updateIndices.Contains(i))
                {
                    var entity = entities[i];
                    //var currentId = metadata.PrimaryKey.Property.GetValue(entity);
                    //if (IsDefaultValue(currentId, metadata.PrimaryKey.Property.PropertyType))
                    //{
                        if (autoGeneratedIds.Count > 0)
                        {
                            var newId = autoGeneratedIds.Dequeue();
                            OrmMapper.SetEntityId(entity, metadata, newId);
                        }
                    //}
                    createdEntities.Add(entity);
                }
            }
        }
        catch (Exception ex)
        {
            throw;
        }
        finally
        {
            await connection.ExecuteAsync($"DROP TABLE IF EXISTS \"{tempTableName}\"", transaction: transaction);
        }
    }

    private async Task CreateTempTableAsync(
    IDbConnection conn,
    IDbTransaction trans,
    ClassMetadata meta,
    List<PropertyMetadata> props,
    string tempTable)
{
    var allowedColumns = new HashSet<string>(
        props.Select(p => p.ColName),
        StringComparer.OrdinalIgnoreCase
    );

    allowedColumns.Add(meta.PrimaryKey.ColName);
    allowedColumns.Add("__row_index");

    var sb = new StringBuilder();

    sb.AppendLine($@"
        CREATE TEMP TABLE ""{tempTable}""
        (LIKE ""{meta.TableName}""
            INCLUDING CONSTRAINTS
            EXCLUDING DEFAULTS
            EXCLUDING GENERATED
            EXCLUDING IDENTITY
        );
    ");

    sb.AppendLine($@"
        ALTER TABLE ""{tempTable}""
        ALTER COLUMN ""{meta.PrimaryKey.ColName}"" DROP NOT NULL;
    ");

    sb.AppendLine($@"
        ALTER TABLE ""{tempTable}""
        ADD COLUMN ""__row_index"" INT;
    ");

    sb.AppendLine($@"
        DO $$
        DECLARE col text;
        BEGIN
            FOR col IN
                SELECT column_name
                FROM information_schema.columns
                WHERE table_name = '{tempTable}'
            LOOP
                IF NOT col = ANY (ARRAY[{string.Join(",", allowedColumns.Select(c => $"'{c}'"))}]) THEN
                    EXECUTE format(
                        'ALTER TABLE ""{tempTable}"" DROP COLUMN %I',
                        col
                    );
                END IF;
            END LOOP;
        END $$;
    ");

    await conn.ExecuteAsync(sb.ToString(), transaction: trans);
}


    private async Task BinaryImportAsync<T>(NpgsqlConnection conn, NpgsqlTransaction trans, List<T> entities, List<PropertyMetadata> props, string tempTable)
    {
        var colNames = new List<string> { "\"__row_index\"", $"\"{props.First(p => p.IsPrimaryKey).ColName}\"" };
        colNames.AddRange(props.Where(p => !p.IsPrimaryKey).Select(p => $"\"{p.ColName}\""));

        var copyCommand = $"COPY \"{tempTable}\" ({string.Join(", ", colNames)}) FROM STDIN (FORMAT BINARY)";

        using (var writer = await conn.BeginBinaryImportAsync(copyCommand))
        {
            for (int i = 0; i < entities.Count; i++)
            {
                var entity = entities[i];
                await writer.StartRowAsync();
                await writer.WriteAsync(i, NpgsqlDbType.Integer);

                var pkProp = props.First(p => p.IsPrimaryKey);
                var pkVal = pkProp.Property.GetValue(entity);
                bool isDefault = IsDefaultValue(pkVal, pkProp.Property.PropertyType);

                if (isDefault) await writer.WriteNullAsync();
                else await writer.WriteAsync(pkVal);

                foreach (var prop in props.Where(p => !p.IsPrimaryKey))
                {
                    object val = null;
                    bool defaultValue = false;
                    if (prop.IsForeignKey && !prop.IsInherited)
                    {
                        var fkEntity = prop.Property.GetValue(entity);
                        if (fkEntity != null)
                        {
                            var fkMeta = OrmMapper.GetMetadata(prop.ForeignKeyType);
                            val = fkMeta.PrimaryKey.Property.GetValue(fkEntity);
                        }
                        defaultValue = IsDefaultValue(val, prop.ForeignKeyType);
                    }
                    else
                    {
                        val = prop.Property.GetValue(entity);
                        defaultValue = prop.IsForeignKey && IsDefaultValue(val, prop.Property.PropertyType);
                    }


                    if (!defaultValue && prop.Converter != null)
                    {
                        val = prop.Converter.FromProvider(val);
                        if (val == null) defaultValue = true;
                    }

                    if (defaultValue) await writer.WriteNullAsync();
                    else
                    {
                        if (prop.CustomField == null) await writer.WriteAsync(val);
                        else await writer.WriteAsync(val, prop.CustomField);
                    }
                }
            }
            await writer.CompleteAsync();
        }
    }

    private bool IsDefaultValue(object val, Type type)
    {
        if (val == null) return true;
        if (type == typeof(string)) return string.IsNullOrEmpty((string)val);
        if (type == typeof(Guid)) return ((Guid)val) == Guid.Empty;
        if (type.IsValueType) return Activator.CreateInstance(type).Equals(val);
        return false;
    }

    private async Task<IEnumerable<MergeResult>> RunMergeAsync(
    IDbConnection conn,
    IDbTransaction trans,
    ClassMetadata meta,
    List<PropertyMetadata> props,
    string tempTable)
    {
        var pk = meta.PrimaryKey.ColName;
        var cols = props.Where(p => !p.IsPrimaryKey)
                        .Select(p => $"\"{p.ColName}\"")
                        .ToList();

        var sb = new StringBuilder();

        sb.AppendLine("WITH updates AS (");
        sb.AppendLine($"    UPDATE \"{meta.TableName}\" t");
        sb.AppendLine($"    SET {string.Join(", ", cols.Select(c => $"{c} = s.{c}"))}");
        sb.AppendLine($"    FROM \"{tempTable}\" s");
        sb.AppendLine($"    WHERE s.\"{pk}\" IS NOT NULL");
        sb.AppendLine($"      AND t.\"{pk}\" = s.\"{pk}\"");
        sb.AppendLine($"    RETURNING s.\"__row_index\" AS RowIndex, t.\"{pk}\" AS Id");
        sb.AppendLine("),");

        sb.AppendLine("inserts AS (");
        sb.AppendLine($"    INSERT INTO \"{meta.TableName}\" ({string.Join(", ", cols)})");
        sb.AppendLine($"    SELECT {string.Join(", ", cols.Select(c => $"s.{c}"))}");
        sb.AppendLine($"    FROM \"{tempTable}\" s");
        sb.AppendLine($"    WHERE NOT EXISTS (");
        sb.AppendLine($"        SELECT 1 FROM updates u WHERE u.RowIndex = s.\"__row_index\"");
        sb.AppendLine($"    )");
        sb.AppendLine($"    RETURNING \"{pk}\" AS Id");
        sb.AppendLine(")");

        sb.AppendLine("SELECT RowIndex, Id, 'UPDATE' AS Type FROM updates");
        sb.AppendLine("UNION ALL");
        sb.AppendLine("SELECT NULL, Id, 'INSERT' AS Type FROM inserts");

        return await conn.QueryAsync<MergeResult>(sb.ToString(), transaction: trans);
    }


    private string GetSqlType(Type type)
    {
        type = Nullable.GetUnderlyingType(type) ?? type;
        if (type == typeof(int)) return "INT";
        if (type == typeof(long)) return "BIGINT";
        if (type == typeof(string)) return "TEXT";
        if (type == typeof(Guid)) return "UUID";
        if (type == typeof(DateTimeOffset)) return "TIMESTAMPZ";
        if (type == typeof(DateTime)) return "TIMESTAMP";
        if (type == typeof(bool)) return "BOOLEAN";
        if (type == typeof(decimal)) return "NUMERIC";
        if (type == typeof(double)) return "DOUBLE PRECISION";
        return "TEXT";
    }
}
public class MergeResult
{
    public int RowIndex { get; set; }
    public object Id { get; set; }
    public string Type { get; set; } // "UPDATE" or "INSERT"
}
